name: mcore5
version: 1.1.4
main: com.massivecraft.mcore5.MCore
load: startup
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  mcore.cmd.usys: {description: manage the universe system, default: false}
  mcore.cmd.usys.multiverse: {description: manage multiverses, default: false}
  mcore.cmd.usys.multiverse.list: {description: list multiverses, default: false}
  mcore.cmd.usys.multiverse.show: {description: show multiverse, default: false}
  mcore.cmd.usys.multiverse.new: {description: create new multiverse, default: false}
  mcore.cmd.usys.multiverse.del: {description: delete multiverse, default: false}
  mcore.cmd.usys.universe: {description: manage universes, default: false}
  mcore.cmd.usys.universe.new: {description: create new universe in multiverse, default: false}
  mcore.cmd.usys.universe.del: {description: delete universe in multiverse, default: false}
  mcore.cmd.usys.universe.clear: {description: clear universe in multiverse, default: false}
  mcore.cmd.usys.world: {description: set a worlds universe in a multiverse, default: false}
  mcore.cmd.usys.aspect: {description: manage aspects, default: false}
  mcore.cmd.usys.aspect.list: {description: list aspects, default: false}
  mcore.cmd.usys.aspect.show: {description: show aspect, default: false}
  mcore.cmd.usys.aspect.use: {description: set multiverse for aspect, default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  mcore.cmd.usys.multiverse.*:
    default: false
    children:
      mcore.cmd.usys.multiverse.list: true
      mcore.cmd.usys.multiverse.show: true
      mcore.cmd.usys.multiverse.new: true
      mcore.cmd.usys.multiverse.del: true
  mcore.cmd.usys.universe.*:
    default: false
    children:
      mcore.cmd.usys.universe.new: true
      mcore.cmd.usys.universe.del: true
      mcore.cmd.usys.universe.clear: true
  mcore.cmd.usys.aspect.*:
    default: false
    children:
      mcore.cmd.usys.aspect.list: true
      mcore.cmd.usys.aspect.show: true
      mcore.cmd.usys.aspect.use: true
  mcore.cmd.usys.*:
    default: false
    children:
      mcore.cmd.usys.multiverse: true
      mcore.cmd.usys.multiverse.*: true
      mcore.cmd.usys.universe: true
      mcore.cmd.usys.universe.*: true
      mcore.cmd.usys.world: true
      mcore.cmd.usys.aspect: true
      mcore.cmd.usys.aspect.*: true
  mcore.cmd.*:
    default: false
    children:
      mcore.cmd.usys: true
      mcore.cmd.usys.*: true
  mcore.*:
    default: false
    children:
      mcore.cmd.*: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  mcore.kit.operator:
    default: op
    children:
      mcore.*: true
  mcore.kit.readonly:
    default: false
    children:
      mcore.cmd.usys: true
      mcore.cmd.usys.multiverse: true
      mcore.cmd.usys.multiverse.list: true
      mcore.cmd.usys.multiverse.show: true
      mcore.cmd.usys.universe: true
      mcore.cmd.usys.aspect: true
      mcore.cmd.usys.aspect.list: true
      mcore.cmd.usys.aspect.show: true